### ISSUE TITLE
Replace doctests by plain unittests.

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.redirector#12]
unittests are cool, doctests are old-school.
I am working on this.

**Comment by djay** [comment]
you can have the best of both worlds by using a test module with doctests split up into method comments so they are isolated.

**Comment by mauritsvanrees** [comment]
Doctests are fine when they are actually documentation that is visible on for example PyPI. In this case it is not.
Anyway, the PR is merged. :-)
