### ISSUE TITLE
Control panel for managing redirects

### ISSUE THREAD

**Issue by staeff** [plone/plone.app.redirector#2]
I see there has been some work to introduce a control panel by @toutpt (branch: toutpt-addui). Since I would have a use case for this, I am wondering if there is a particular reason, why this work was never merged.
I would try to work on this. Any heads up what might be problematic are welcome.

**Comment by davisagli** [comment]
There is also a control panel for this in Products.RedirectionTool.

**Comment by datakurre** [comment]
https://github.com/plone/Products.CMFPlone/tree/plip-1486-redirection

**Comment by mauritsvanrees** [comment]
[PLIP 1486](https://github.com/plone/Products.CMFPlone/issues/1486#issuecomment-462779096) has been merged today. Thank you @staeff for starting the work yourself last year! 👍

**Comment by staeff** [comment]
Thank you @mauritsvanrees for finishing the work on this plip!
