### ISSUE TITLE
Redirect with url fragments get wrong quote encoding

### ISSUE THREAD

**Issue by Gomez** [plone/plone.app.redirector#3]
I added a redirect with Products.RedirectTool:

```
/en/xyy to /de/hochdruckreiniger#b_start=0&c5=500-bar
```

This comes out:
/de/hochdruckreiniger%23b_start%3D0%26c5%3D500-bar
and dont work (in eea.facednavigation).

**Comment by gforcada** [comment]
Is it in the meantime fixed? 🤔 🍀 

Feel free to re-open if it is not the case.

**Comment by mauritsvanrees** [comment]
Probably it is not fixed. But the redirects are not meant to be this way. They should point to an actual content item, not to a url, or a view, or with query parameters or a hash like here.
If it *does* happen to work: be happy for now, but don't count on this working always in the future.
